AWSTemplateFormatVersion: '2010-09-09'
Description: Role to enable API Gateway logging to CloudWatch

Parameters:
  Environment:
    Type: String
    Default: prod
    Description: ApiGatewayLoggingRole

Resources:
  ApiGatewayLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${RoleName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service: apigateway.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
