AWSTemplateFormatVersion: '2010-09-09'
Description: Standard resources for management accounts

Parameters:
  Environment:
    Type: String
    Default: prod
    Description: Environment identifier
  Identifier:
    Type: String
    Default: Streetlight
    Description: Unique identifier for resources created in PascalCase
  IdentifierLower:
    Type: String
    Default: streetlight
    Description: Lowercase value of Identifier
  AdminRoles:
    Type: String
    Description: Comma separated list of admin role ARNs
  PipelineRoles:
    Type: String
    Description: Comma separated list of pipeline role ARNs

Resources:
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Identifier}AdminRole'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref Identifier
        - Key: Role
          Value: !Sub '${IdentifierLower}-admin-role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${Identifier}AdminGroup'
      Policies:
        - PolicyName: !Sub 'Assume${Identifier}AdminRole'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource:  !Split [ ',', !Ref AdminRoles ]
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource:  !GetAtt AdminRole.Arn


  PipelineGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${Identifier}PipelinenGroup'
      Policies:
        - PolicyName: !Sub 'Assume${Identifier}PipelineRole'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource:  !Split [ ',', !Ref PipelineRoles ]

  PipelineUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub '${IdentifierLower}-pipeline-user'
      Groups:
        - !Ref PipelineGroup
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref Identifier

  PipelineUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 1
      Status: Active
      UserName: !Ref PipelineUser

  PipelineUserSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${Identifier}PipelineUserSecretKey
      SecretString: !Sub '{"aws_access_key_id": "${PipelineUserAccessKey}", "aws_secret_access_key": "${PipelineUserAccessKey.SecretAccessKey}"}'

Outputs:
  PipelineUser:
    Description: ARN of the Pipeline IAM User
    Value: !GetAtt PipelineUser.Arn

  PipelineUserSecretKey:
    Description: AWS Access Key and Secret Key of pipeline user.
    Value: !Ref PipelineUserSecretKey
